// <auto-generated />
using ComputerComponentShop.Models.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerComponentShop.Migrations
{
    [DbContext(typeof(ComputerComponentContext))]
    [Migration("20250603183656_AllComponentsV2")]
    partial class AllComponentsV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.AirCooler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FanSize")
                        .HasColumnType("int");

                    b.Property<int>("FanSpeed")
                        .HasColumnType("int");

                    b.Property<bool>("HasRgb")
                        .HasColumnType("bit");

                    b.Property<int>("HeatPipes")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxTdpWatts")
                        .HasColumnType("int");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NoiseLevel")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<string>("SocketCompatibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AirCoolers");

                    b.HasData(
                        new
                        {
                            Id = 701,
                            Description = "Balanced dual-tower cooler with stylish design.",
                            FanSize = 120,
                            FanSpeed = 1850,
                            HasRgb = true,
                            HeatPipes = 6,
                            Height = 160.0,
                            Manufacturer = "DeepCool",
                            MaxTdpWatts = 260,
                            ModelNumber = "R-AK620-BKNNMT-G-1",
                            Name = "DeepCool AK620",
                            NoiseLevel = 28.0,
                            Price = 799m,
                            ProductCategory = 8,
                            SocketCompatibility = "AM4, LGA1700, LGA1200"
                        },
                        new
                        {
                            Id = 702,
                            Description = "High-performance cooler with dual fans at a great price.",
                            FanSize = 120,
                            FanSpeed = 1550,
                            HasRgb = false,
                            HeatPipes = 6,
                            Height = 157.0,
                            Manufacturer = "Thermalright",
                            MaxTdpWatts = 220,
                            ModelNumber = "PA120",
                            Name = "Thermalright Peerless Assassin 120",
                            NoiseLevel = 25.600000000000001,
                            Price = 649m,
                            ProductCategory = 8,
                            SocketCompatibility = "AM4, LGA1700"
                        },
                        new
                        {
                            Id = 703,
                            Description = "Efficient dual-fan cooler with low noise and height.",
                            FanSize = 120,
                            FanSpeed = 1200,
                            HasRgb = true,
                            HeatPipes = 6,
                            Height = 154.5,
                            Manufacturer = "Scythe",
                            MaxTdpWatts = 200,
                            ModelNumber = "SCFM-2000",
                            Name = "Scythe Fuma 2 Rev.B",
                            NoiseLevel = 23.0,
                            Price = 699m,
                            ProductCategory = 8,
                            SocketCompatibility = "AM4, LGA1700"
                        },
                        new
                        {
                            Id = 704,
                            Description = "Popular budget-friendly cooler with solid performance.",
                            FanSize = 120,
                            FanSpeed = 1800,
                            HasRgb = false,
                            HeatPipes = 4,
                            Height = 159.0,
                            Manufacturer = "Cooler Master",
                            MaxTdpWatts = 150,
                            ModelNumber = "RR-212S-20PK-R1",
                            Name = "Cooler Master Hyper 212 Black Edition",
                            NoiseLevel = 26.0,
                            Price = 499m,
                            ProductCategory = 8,
                            SocketCompatibility = "AM4, LGA1700"
                        },
                        new
                        {
                            Id = 705,
                            Description = "Silent dual-tower cooler with excellent heat dissipation.",
                            FanSize = 135,
                            FanSpeed = 1500,
                            HasRgb = true,
                            HeatPipes = 7,
                            Height = 162.0,
                            Manufacturer = "be quiet!",
                            MaxTdpWatts = 250,
                            ModelNumber = "BK022",
                            Name = "be quiet! Dark Rock Pro 4",
                            NoiseLevel = 24.300000000000001,
                            Price = 899m,
                            ProductCategory = 8,
                            SocketCompatibility = "AM4, LGA1700"
                        },
                        new
                        {
                            Id = 706,
                            Description = "High-end dual-tower air cooler with excellent performance.",
                            FanSize = 140,
                            FanSpeed = 1500,
                            HasRgb = true,
                            HeatPipes = 6,
                            Height = 165.0,
                            Manufacturer = "Noctua",
                            MaxTdpWatts = 220,
                            ModelNumber = "NH-D15",
                            Name = "Noctua NH-D15",
                            NoiseLevel = 24.600000000000001,
                            Price = 999m,
                            ProductCategory = 8,
                            SocketCompatibility = "AM4, LGA1700, LGA1200"
                        });
                });

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.Chassi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherboardSupport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<string>("TowerSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WaterCoolerSupport")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Chassis");

                    b.HasData(
                        new
                        {
                            Id = 901,
                            Description = "Mid-tower with minimalist design and tempered glass side panel.",
                            FormFactor = "ATX",
                            Manufacturer = "NZXT",
                            ModelNumber = "CA-H510B-B1",
                            MotherboardSupport = "ATX, Micro-ATX, Mini-ITX",
                            Name = "NZXT H510",
                            Price = 899m,
                            ProductCategory = 9,
                            TowerSize = "Mid Tower",
                            WaterCoolerSupport = true
                        },
                        new
                        {
                            Id = 902,
                            Description = "Compact mid-tower with excellent airflow and modern design.",
                            FormFactor = "ATX",
                            Manufacturer = "Fractal Design",
                            ModelNumber = "FD-CA-MESH-C-BKO-TG",
                            MotherboardSupport = "ATX, Micro-ATX, Mini-ITX",
                            Name = "Fractal Design Meshify C",
                            Price = 999m,
                            ProductCategory = 9,
                            TowerSize = "Mid Tower",
                            WaterCoolerSupport = true
                        },
                        new
                        {
                            Id = 903,
                            Description = "Compact case with modular design and dust filters.",
                            FormFactor = "Micro-ATX",
                            Manufacturer = "Cooler Master",
                            ModelNumber = "MCB-Q300L-KANN-S00",
                            MotherboardSupport = "Micro-ATX, Mini-ITX",
                            Name = "Cooler Master MasterBox Q300L",
                            Price = 599m,
                            ProductCategory = 9,
                            TowerSize = "Mini Tower",
                            WaterCoolerSupport = false
                        },
                        new
                        {
                            Id = 904,
                            Description = "Showcase chassis with dual-chamber design and tempered glass.",
                            FormFactor = "ATX",
                            Manufacturer = "Lian Li",
                            ModelNumber = "PC-O11DW",
                            MotherboardSupport = "ATX, Micro-ATX, Mini-ITX, E-ATX",
                            Name = "Lian Li PC-O11 Dynamic",
                            Price = 1399m,
                            ProductCategory = 9,
                            TowerSize = "Mid Tower",
                            WaterCoolerSupport = true
                        },
                        new
                        {
                            Id = 905,
                            Description = "High airflow case with mesh front panel and RGB lighting.",
                            FormFactor = "ATX",
                            Manufacturer = "Phanteks",
                            ModelNumber = "PH-EC400ATG_DWT01",
                            MotherboardSupport = "ATX, Micro-ATX, Mini-ITX",
                            Name = "Phanteks Eclipse P400A",
                            Price = 1099m,
                            ProductCategory = 9,
                            TowerSize = "Mid Tower",
                            WaterCoolerSupport = true
                        },
                        new
                        {
                            Id = 906,
                            Description = "Cube-style micro ATX case with versatile layout options.",
                            FormFactor = "Micro-ATX",
                            Manufacturer = "Thermaltake",
                            ModelNumber = "CA-1D5-00S1WN-00",
                            MotherboardSupport = "Micro-ATX, Mini-ITX",
                            Name = "Thermaltake Core V21",
                            Price = 649m,
                            ProductCategory = 9,
                            TowerSize = "Micro Tower",
                            WaterCoolerSupport = true
                        });
                });

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.GraphicCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<int>("VramMemory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GPUs");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Chipset = "Ada Lovelace",
                            Description = "High-end gaming GPU with ray tracing and DLSS 3.",
                            Manufacturer = "NVIDIA",
                            ModelNumber = "RTX4070TI-12G",
                            Name = "NVIDIA GeForce RTX 4070 Ti",
                            Price = 9290m,
                            ProductCategory = 4,
                            VramMemory = 12
                        },
                        new
                        {
                            Id = 202,
                            Chipset = "RDNA 3",
                            Description = "Powerful RDNA 3 architecture with high VRAM for 4K gaming.",
                            Manufacturer = "AMD",
                            ModelNumber = "RX7900XT-20G",
                            Name = "AMD Radeon RX 7900 XT",
                            Price = 8790m,
                            ProductCategory = 4,
                            VramMemory = 20
                        },
                        new
                        {
                            Id = 203,
                            Chipset = "Ampere",
                            Description = "Budget-friendly GPU with solid 1080p performance.",
                            Manufacturer = "NVIDIA",
                            ModelNumber = "RTX3060-12G",
                            Name = "NVIDIA GeForce RTX 3060",
                            Price = 3490m,
                            ProductCategory = 4,
                            VramMemory = 12
                        },
                        new
                        {
                            Id = 204,
                            Chipset = "RDNA 2",
                            Description = "Strong 1440p performance with fast memory bandwidth.",
                            Manufacturer = "AMD",
                            ModelNumber = "RX6750XT-12G",
                            Name = "AMD Radeon RX 6750 XT",
                            Price = 4590m,
                            ProductCategory = 4,
                            VramMemory = 12
                        },
                        new
                        {
                            Id = 205,
                            Chipset = "Alchemist",
                            Description = "Intel's high-end GPU with Xe HPG architecture.",
                            Manufacturer = "Intel",
                            ModelNumber = "ARC-A770-16G",
                            Name = "Intel Arc A770",
                            Price = 3990m,
                            ProductCategory = 4,
                            VramMemory = 16
                        },
                        new
                        {
                            Id = 206,
                            Chipset = "Turing",
                            Description = "Reliable mid-range GPU for 1080p gaming.",
                            Manufacturer = "NVIDIA",
                            ModelNumber = "GTX1660S-6G",
                            Name = "NVIDIA GeForce GTX 1660 Super",
                            Price = 2290m,
                            ProductCategory = 4,
                            VramMemory = 6
                        });
                });

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.Hdd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapacityGb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpectedLifetime")
                        .HasColumnType("int");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<int>("ReadSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Rpm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WriteSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HDDs");

                    b.HasData(
                        new
                        {
                            Id = 501,
                            CapacityGb = "2000",
                            Description = "Reliable desktop hard drive with large storage capacity",
                            ExpectedLifetime = 1000000,
                            Interface = "SATA",
                            Manufacturer = "Seagate",
                            ModelNumber = "ST2000DM008",
                            Name = "Seagate Barracuda",
                            Price = 749m,
                            ProductCategory = 10,
                            ReadSpeed = 160,
                            Rpm = "7200",
                            WriteSpeed = 150
                        },
                        new
                        {
                            Id = 502,
                            CapacityGb = "1000",
                            Description = "Standard desktop HDD ideal for everyday computing",
                            ExpectedLifetime = 800000,
                            Interface = "SATA",
                            Manufacturer = "Western Digital",
                            ModelNumber = "WD10EZEX",
                            Name = "WD Blue",
                            Price = 699m,
                            ProductCategory = 10,
                            ReadSpeed = 150,
                            Rpm = "7200",
                            WriteSpeed = 140
                        },
                        new
                        {
                            Id = 503,
                            CapacityGb = "2000",
                            Description = "Performance HDD for desktop systems",
                            ExpectedLifetime = 1000000,
                            Interface = "SATA",
                            Manufacturer = "Toshiba",
                            ModelNumber = "HDWD120UZSVA",
                            Name = "Toshiba P300",
                            Price = 829m,
                            ProductCategory = 10,
                            ReadSpeed = 160,
                            Rpm = "7200",
                            WriteSpeed = 150
                        },
                        new
                        {
                            Id = 504,
                            CapacityGb = "4000",
                            Description = "NAS-optimized HDD with high durability",
                            ExpectedLifetime = 1800000,
                            Interface = "SATA",
                            Manufacturer = "Seagate",
                            ModelNumber = "ST4000VN008",
                            Name = "Seagate IronWolf",
                            Price = 1299m,
                            ProductCategory = 10,
                            ReadSpeed = 180,
                            Rpm = "5900",
                            WriteSpeed = 170
                        },
                        new
                        {
                            Id = 505,
                            CapacityGb = "2000",
                            Description = "High-performance HDD for gaming and media workstations",
                            ExpectedLifetime = 1200000,
                            Interface = "SATA",
                            Manufacturer = "Western Digital",
                            ModelNumber = "WD2003FZEX",
                            Name = "WD Black Performance",
                            Price = 999m,
                            ProductCategory = 10,
                            ReadSpeed = 180,
                            Rpm = "7200",
                            WriteSpeed = 160
                        },
                        new
                        {
                            Id = 506,
                            CapacityGb = "10000",
                            Description = "Enterprise-grade hard disk drive for long-term storage",
                            ExpectedLifetime = 2500000,
                            Interface = "SATA",
                            Manufacturer = "HGST",
                            ModelNumber = "HUH721010ALE600",
                            Name = "HGST Ultrastar",
                            Price = 1399m,
                            ProductCategory = 10,
                            ReadSpeed = 210,
                            Rpm = "7200",
                            WriteSpeed = 200
                        });
                });

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("M2Slots")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemmoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Chipset = "B650",
                            Description = "Micro-ATX motherboard for AMD Ryzen with PCIe 4.0 and DDR5 support.",
                            FormFactor = "Micro-ATX",
                            M2Slots = 2,
                            Manufacturer = "MSI",
                            MemmoryType = "DDR5",
                            ModelNumber = "B650M-MORTAR-WIFI",
                            Name = "MSI B650M Mortar WiFi",
                            Price = 1990m,
                            ProductCategory = 0,
                            Socket = "AM5"
                        },
                        new
                        {
                            Id = 102,
                            Chipset = "Z790",
                            Description = "Premium Intel Z790 motherboard with high-end features for gamers.",
                            FormFactor = "ATX",
                            M2Slots = 4,
                            Manufacturer = "ASUS",
                            MemmoryType = "DDR5",
                            ModelNumber = "90MB1CW0-M0EAY0",
                            Name = "ASUS ROG Strix Z790-E Gaming WiFi",
                            Price = 4290m,
                            ProductCategory = 0,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 103,
                            Chipset = "B550",
                            Description = "Affordable AM4 motherboard with strong VRM and PCIe 4.0.",
                            FormFactor = "ATX",
                            M2Slots = 2,
                            Manufacturer = "Gigabyte",
                            MemmoryType = "DDR4",
                            ModelNumber = "B550-AORUS-ELITE-V2",
                            Name = "Gigabyte B550 AORUS Elite V2",
                            Price = 1390m,
                            ProductCategory = 0,
                            Socket = "AM4"
                        },
                        new
                        {
                            Id = 104,
                            Chipset = "B460",
                            Description = "Entry-level Intel motherboard with solid features for budget builds.",
                            FormFactor = "Micro-ATX",
                            M2Slots = 1,
                            Manufacturer = "ASUS",
                            MemmoryType = "DDR4",
                            ModelNumber = "B460M-A",
                            Name = "ASUS PRIME B460M-A",
                            Price = 990m,
                            ProductCategory = 0,
                            Socket = "LGA1200"
                        },
                        new
                        {
                            Id = 105,
                            Chipset = "X670E",
                            Description = "Flagship AM5 motherboard with PCIe 5.0 and robust power delivery.",
                            FormFactor = "ATX",
                            M2Slots = 4,
                            Manufacturer = "ASRock",
                            MemmoryType = "DDR5",
                            ModelNumber = "X670E-TAICHI",
                            Name = "ASRock X670E Taichi",
                            Price = 5890m,
                            ProductCategory = 0,
                            Socket = "AM5"
                        },
                        new
                        {
                            Id = 106,
                            Chipset = "Z690",
                            Description = "Well-balanced Z690 motherboard with DDR4 support for 12th gen Intel CPUs.",
                            FormFactor = "ATX",
                            M2Slots = 3,
                            Manufacturer = "MSI",
                            MemmoryType = "DDR4",
                            ModelNumber = "Z690-A-PRO-DDR4",
                            Name = "MSI PRO Z690-A DDR4",
                            Price = 2190m,
                            ProductCategory = 0,
                            Socket = "LGA1700"
                        });
                });

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.PowerSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EfficiencyRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formfactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modularity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PowerSupplies");

                    b.HasData(
                        new
                        {
                            Id = 301,
                            Description = "750W 80+ Gold Certified Fully Modular",
                            EfficiencyRating = "80+ Gold",
                            Formfactor = "ATX",
                            Manufacturer = "Corsair",
                            ModelNumber = "CP-9020179-EU",
                            Modularity = "Modular",
                            Name = "Corsair RM750x",
                            Price = 1299m,
                            ProductCategory = 1,
                            Wattage = 750
                        },
                        new
                        {
                            Id = 302,
                            Description = "650W 80+ Gold Fully Modular PSU",
                            EfficiencyRating = "80+ Gold",
                            Formfactor = "ATX",
                            Manufacturer = "Seasonic",
                            ModelNumber = "FOCUS-GX-650",
                            Modularity = "Modular",
                            Name = "Seasonic Focus GX-650",
                            Price = 1149m,
                            ProductCategory = 1,
                            Wattage = 650
                        },
                        new
                        {
                            Id = 303,
                            Description = "850W 80+ Platinum Fully Modular",
                            EfficiencyRating = "80+ Platinum",
                            Formfactor = "ATX",
                            Manufacturer = "be quiet!",
                            ModelNumber = "BN641",
                            Modularity = "Modular",
                            Name = "be quiet! Straight Power 11",
                            Price = 1799m,
                            ProductCategory = 1,
                            Wattage = 850
                        },
                        new
                        {
                            Id = 304,
                            Description = "600W 80+ Bronze Non-Modular",
                            EfficiencyRating = "80+ Bronze",
                            Formfactor = "ATX",
                            Manufacturer = "EVGA",
                            ModelNumber = "100-BR-0600-K1",
                            Modularity = "Non-Modular",
                            Name = "EVGA 600 BR",
                            Price = 699m,
                            ProductCategory = 1,
                            Wattage = 600
                        },
                        new
                        {
                            Id = 305,
                            Description = "550W 80+ Bronze Semi Modular",
                            EfficiencyRating = "80+ Bronze",
                            Formfactor = "ATX",
                            Manufacturer = "Cooler Master",
                            ModelNumber = "MPX-5501-ACAAB",
                            Modularity = "Semi-Modular",
                            Name = "Cooler Master MWE Bronze 550",
                            Price = 749m,
                            ProductCategory = 1,
                            Wattage = 550
                        },
                        new
                        {
                            Id = 306,
                            Description = "760W 80+ Platinum Fully Modular",
                            EfficiencyRating = "80+ Platinum",
                            Formfactor = "ATX",
                            Manufacturer = "Fractal Design",
                            ModelNumber = "FD-PSU-IONP-760P-BK",
                            Modularity = "Modular",
                            Name = "Fractal Design Ion+ 760P",
                            Price = 1549m,
                            ProductCategory = 1,
                            Wattage = 760
                        });
                });

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.Processor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BaseClockSpeed")
                        .HasColumnType("float");

                    b.Property<double>("BoostClockSpeed")
                        .HasColumnType("float");

                    b.Property<int>("CpuCores")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Processors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseClockSpeed = 4.7000000000000002,
                            BoostClockSpeed = 5.2999999999999998,
                            CpuCores = 6,
                            Description = "6-core processor with high single-thread performance.",
                            Manufacturer = "AMD",
                            ModelNumber = "100-100000593WOF",
                            Name = "AMD Ryzen 5 7600X",
                            Price = 2790m,
                            ProductCategory = 3,
                            Socket = "AM5",
                            Threads = 12
                        },
                        new
                        {
                            Id = 2,
                            BaseClockSpeed = 3.5,
                            BoostClockSpeed = 5.0999999999999996,
                            CpuCores = 14,
                            Description = "Hybrid architecture with performance and efficiency cores.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8071513600K",
                            Name = "Intel Core i5-13600K",
                            Price = 3290m,
                            ProductCategory = 3,
                            Socket = "LGA1700",
                            Threads = 20
                        },
                        new
                        {
                            Id = 3,
                            BaseClockSpeed = 3.3999999999999999,
                            BoostClockSpeed = 5.5999999999999996,
                            CpuCores = 20,
                            Description = "Great balance for gaming and productivity workloads.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8071514700K",
                            Name = "Intel Core i7-14700K",
                            Price = 4490m,
                            ProductCategory = 3,
                            Socket = "LGA1700",
                            Threads = 28
                        },
                        new
                        {
                            Id = 4,
                            BaseClockSpeed = 3.7999999999999998,
                            BoostClockSpeed = 4.7000000000000002,
                            CpuCores = 8,
                            Description = "High-performance AM4 processor with 8 cores.",
                            Manufacturer = "AMD",
                            ModelNumber = "100-100000063WOF",
                            Name = "AMD Ryzen 7 5800X",
                            Price = 2690m,
                            ProductCategory = 3,
                            Socket = "AM4",
                            Threads = 16
                        },
                        new
                        {
                            Id = 5,
                            BaseClockSpeed = 3.7000000000000002,
                            BoostClockSpeed = 4.7999999999999998,
                            CpuCores = 12,
                            Description = "Powerful 12-core AM4 processor for gaming and productivity.",
                            Manufacturer = "AMD",
                            ModelNumber = "100-100000061WOF",
                            Name = "AMD Ryzen 9 5900X",
                            Price = 4490m,
                            ProductCategory = 3,
                            Socket = "AM4",
                            Threads = 24
                        },
                        new
                        {
                            Id = 6,
                            BaseClockSpeed = 3.2000000000000002,
                            BoostClockSpeed = 6.0,
                            CpuCores = 24,
                            Description = "Flagship processor with maximum performance for enthusiasts.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8071514900K",
                            Name = "Intel Core i9-14900K",
                            Price = 6990m,
                            ProductCategory = 3,
                            Socket = "LGA1700",
                            Threads = 32
                        },
                        new
                        {
                            Id = 7,
                            BaseClockSpeed = 2.8999999999999999,
                            BoostClockSpeed = 4.2999999999999998,
                            CpuCores = 6,
                            Description = "6-core budget-friendly CPU, great for entry-level gaming.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8070110400F",
                            Name = "Intel Core i5-10400F",
                            Price = 1390m,
                            ProductCategory = 3,
                            Socket = "LGA1200",
                            Threads = 12
                        },
                        new
                        {
                            Id = 8,
                            BaseClockSpeed = 3.8999999999999999,
                            BoostClockSpeed = 4.9000000000000004,
                            CpuCores = 6,
                            Description = "6-core 11th gen CPU with strong single-core performance.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8070811600K",
                            Name = "Intel Core i5-11600K",
                            Price = 2190m,
                            ProductCategory = 3,
                            Socket = "LGA1200",
                            Threads = 12
                        });
                });

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.Ram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityGb")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<int>("SpeedMhz")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rams");

                    b.HasData(
                        new
                        {
                            Id = 801,
                            CapacityGb = 32,
                            Description = "Gaming RAM with vibrant RGB lighting.",
                            Latency = "CL34",
                            Manufacturer = "TeamGroup",
                            ModelNumber = "FF3D532G7200HC34ADC01",
                            Name = "TeamGroup T-Force Delta RGB",
                            Price = 1599m,
                            ProductCategory = 2,
                            SpeedMhz = 7200,
                            Type = "DDR5"
                        },
                        new
                        {
                            Id = 802,
                            CapacityGb = 16,
                            Description = "Performance RAM without the flash.",
                            Latency = "CL18",
                            Manufacturer = "Patriot",
                            ModelNumber = "PVS416G360C8K",
                            Name = "Patriot Viper Steel",
                            Price = 1199m,
                            ProductCategory = 2,
                            SpeedMhz = 3600,
                            Type = "DDR4"
                        },
                        new
                        {
                            Id = 803,
                            CapacityGb = 32,
                            Description = "Premium RAM with powerful RGB and speed.",
                            Latency = "CL36",
                            Manufacturer = "Corsair",
                            ModelNumber = "CMT32GX5M2B5600C36",
                            Name = "Corsair Dominator Platinum RGB",
                            Price = 1799m,
                            ProductCategory = 2,
                            SpeedMhz = 5600,
                            Type = "DDR5"
                        },
                        new
                        {
                            Id = 804,
                            CapacityGb = 16,
                            Description = "Reliable RAM for gaming builds.",
                            Latency = "CL16",
                            Manufacturer = "Kingston",
                            ModelNumber = "KF432C16BBK2/16",
                            Name = "Kingston Fury Beast",
                            Price = 749m,
                            ProductCategory = 2,
                            SpeedMhz = 3200,
                            Type = "DDR4"
                        },
                        new
                        {
                            Id = 805,
                            CapacityGb = 16,
                            Description = "Stylish RGB RAM with high clock speeds.",
                            Latency = "CL18",
                            Manufacturer = "G.Skill",
                            ModelNumber = "F4-3600C18D-16GTZR",
                            Name = "G.Skill Trident Z RGB",
                            Price = 1399m,
                            ProductCategory = 2,
                            SpeedMhz = 3600,
                            Type = "DDR4"
                        },
                        new
                        {
                            Id = 806,
                            CapacityGb = 16,
                            Description = "High-performance DDR4 memory for gaming and multitasking.",
                            Latency = "CL16",
                            Manufacturer = "Corsair",
                            ModelNumber = "CMK16GX4M2B3200C16",
                            Name = "Corsair Vengeance LPX",
                            Price = 899m,
                            ProductCategory = 2,
                            SpeedMhz = 3200,
                            Type = "DDR4"
                        });
                });

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.SolidStateDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapacityGb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpectedLifetime")
                        .HasColumnType("int");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<int>("ReadSpeed")
                        .HasColumnType("int");

                    b.Property<int>("WriteSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SSDs");

                    b.HasData(
                        new
                        {
                            Id = 401,
                            CapacityGb = "1000",
                            Description = "NVMe M.2 SSD with high-performance Gen4 speed",
                            ExpectedLifetime = 1500000,
                            FormFactor = "M.2",
                            Interface = "NVMe",
                            Manufacturer = "Samsung",
                            ModelNumber = "MZ-V8P1T0BW",
                            Name = "Samsung 980 PRO",
                            Price = 1599m,
                            ProductCategory = 6,
                            ReadSpeed = 7000,
                            WriteSpeed = 5000
                        },
                        new
                        {
                            Id = 402,
                            CapacityGb = "1000",
                            Description = "Reliable 2.5'' SATA SSD with integrated power loss immunity",
                            ExpectedLifetime = 1800000,
                            FormFactor = "2.5",
                            Interface = "SATA",
                            Manufacturer = "Crucial",
                            ModelNumber = "CT1000MX500SSD1",
                            Name = "Crucial MX500",
                            Price = 899m,
                            ProductCategory = 6,
                            ReadSpeed = 560,
                            WriteSpeed = 510
                        },
                        new
                        {
                            Id = 403,
                            CapacityGb = "1000",
                            Description = "High-end PCIe Gen4 NVMe SSD for gaming",
                            ExpectedLifetime = 1600000,
                            FormFactor = "M.2",
                            Interface = "NVMe",
                            Manufacturer = "Western Digital",
                            ModelNumber = "WDS100T2X0E",
                            Name = "WD Black SN850X",
                            Price = 1399m,
                            ProductCategory = 6,
                            ReadSpeed = 7300,
                            WriteSpeed = 6300
                        },
                        new
                        {
                            Id = 404,
                            CapacityGb = "480",
                            Description = "Budget-friendly SATA SSD",
                            ExpectedLifetime = 1000000,
                            FormFactor = "2.5",
                            Interface = "SATA",
                            Manufacturer = "Kingston",
                            ModelNumber = "SA400S37/480G",
                            Name = "Kingston A400",
                            Price = 499m,
                            ProductCategory = 6,
                            ReadSpeed = 500,
                            WriteSpeed = 450
                        },
                        new
                        {
                            Id = 405,
                            CapacityGb = "1000",
                            Description = "QLC NVMe SSD for everyday computing",
                            ExpectedLifetime = 1000000,
                            FormFactor = "M.2",
                            Interface = "NVMe",
                            Manufacturer = "Intel",
                            ModelNumber = "SSDPEKNU010TZX1",
                            Name = "Intel 670p",
                            Price = 849m,
                            ProductCategory = 6,
                            ReadSpeed = 3500,
                            WriteSpeed = 2700
                        },
                        new
                        {
                            Id = 406,
                            CapacityGb = "1000",
                            Description = "M.2 NVMe SSD with PCIe Gen4 support",
                            ExpectedLifetime = 1400000,
                            FormFactor = "M.2",
                            Interface = "NVMe",
                            Manufacturer = "Sabrent",
                            ModelNumber = "SB-RKTQ4-1TB",
                            Name = "Sabrent Rocket Q4",
                            Price = 1299m,
                            ProductCategory = 6,
                            ReadSpeed = 4700,
                            WriteSpeed = 1800
                        });
                });

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.WaterCooler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FanSize")
                        .HasColumnType("int");

                    b.Property<bool>("HasRgb")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxTdpWatts")
                        .HasColumnType("int");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NoiseLevel")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<int>("PumpSpeed")
                        .HasColumnType("int");

                    b.Property<int>("RadiatorSize")
                        .HasColumnType("int");

                    b.Property<string>("SocketCompatibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WaterCoolers");

                    b.HasData(
                        new
                        {
                            Id = 601,
                            Description = "Premium 360mm AIO with high RPM pump and vivid RGB.",
                            FanSize = 120,
                            HasRgb = true,
                            Manufacturer = "EKWB",
                            MaxTdpWatts = 350,
                            ModelNumber = "3831109863489",
                            Name = "EK-AIO Elite 360 D-RGB",
                            NoiseLevel = 29.0,
                            Price = 2699m,
                            ProductCategory = 7,
                            PumpSpeed = 3100,
                            RadiatorSize = 360,
                            SocketCompatibility = "AM4, LGA1700, LGA1200"
                        },
                        new
                        {
                            Id = 602,
                            Description = "Powerful cooling with integrated VRM fan.",
                            FanSize = 140,
                            HasRgb = false,
                            Manufacturer = "Arctic",
                            MaxTdpWatts = 250,
                            ModelNumber = "ACFRE00063A",
                            Name = "Arctic Liquid Freezer II 280",
                            NoiseLevel = 22.5,
                            Price = 1299m,
                            ProductCategory = 7,
                            PumpSpeed = 2000,
                            RadiatorSize = 280,
                            SocketCompatibility = "AM4, LGA1700"
                        },
                        new
                        {
                            Id = 603,
                            Description = "Budget-friendly 240mm AIO cooler with RGB fans.",
                            FanSize = 120,
                            HasRgb = true,
                            Manufacturer = "Cooler Master",
                            MaxTdpWatts = 200,
                            ModelNumber = "MLW-D24M-A18PC-R2",
                            Name = "Cooler Master MasterLiquid ML240L V2",
                            NoiseLevel = 27.0,
                            Price = 999m,
                            ProductCategory = 7,
                            PumpSpeed = 2600,
                            RadiatorSize = 240,
                            SocketCompatibility = "AM4, LGA1700, LGA1200"
                        },
                        new
                        {
                            Id = 604,
                            Description = "Ultra-quiet 360mm AIO water cooler for powerful CPUs.",
                            FanSize = 120,
                            HasRgb = false,
                            Manufacturer = "be quiet!",
                            MaxTdpWatts = 300,
                            ModelNumber = "BW011",
                            Name = "be quiet! Silent Loop 2",
                            NoiseLevel = 20.399999999999999,
                            Price = 2299m,
                            ProductCategory = 7,
                            PumpSpeed = 2800,
                            RadiatorSize = 360,
                            SocketCompatibility = "AM4, LGA1700, TR4"
                        },
                        new
                        {
                            Id = 605,
                            Description = "AIO 280mm CPU cooler with RGB and quiet operation.",
                            FanSize = 140,
                            HasRgb = true,
                            Manufacturer = "NZXT",
                            MaxTdpWatts = 280,
                            ModelNumber = "RL-KRX63-01",
                            Name = "NZXT Kraken X63",
                            NoiseLevel = 21.5,
                            Price = 1899m,
                            ProductCategory = 7,
                            PumpSpeed = 3000,
                            RadiatorSize = 280,
                            SocketCompatibility = "AM4, LGA1200, LGA1700"
                        },
                        new
                        {
                            Id = 606,
                            Description = "High-performance 240mm liquid CPU cooler with RGB fans.",
                            FanSize = 120,
                            HasRgb = true,
                            Manufacturer = "Corsair",
                            MaxTdpWatts = 250,
                            ModelNumber = "CW-9060039-WW",
                            Name = "Corsair H100i RGB Platinum",
                            NoiseLevel = 25.0,
                            Price = 1599m,
                            ProductCategory = 7,
                            PumpSpeed = 2700,
                            RadiatorSize = 240,
                            SocketCompatibility = "AM4, LGA1200, LGA1700"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
