// <auto-generated />
using ComputerComponentShop.Models.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerComponentShop.Migrations
{
    [DbContext(typeof(ComputerComponentContext))]
    [Migration("20250602200259_Processors")]
    partial class Processors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComputerComponentShop.Models.ProductClasses.Processor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BaseClockSpeed")
                        .HasColumnType("float");

                    b.Property<double>("BoostClockSpeed")
                        .HasColumnType("float");

                    b.Property<int>("CpuCores")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Processors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseClockSpeed = 4.7000000000000002,
                            BoostClockSpeed = 5.2999999999999998,
                            CpuCores = 6,
                            Description = "6-core processor with high single-thread performance.",
                            Manufacturer = "AMD",
                            ModelNumber = "100-100000593WOF",
                            Name = "AMD Ryzen 5 7600X",
                            Price = 2790m,
                            ProductCategory = 3,
                            Socket = "AM5",
                            Threads = 12
                        },
                        new
                        {
                            Id = 2,
                            BaseClockSpeed = 3.5,
                            BoostClockSpeed = 5.0999999999999996,
                            CpuCores = 14,
                            Description = "Hybrid architecture with performance and efficiency cores.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8071513600K",
                            Name = "Intel Core i5-13600K",
                            Price = 3290m,
                            ProductCategory = 3,
                            Socket = "LGA1700",
                            Threads = 20
                        },
                        new
                        {
                            Id = 3,
                            BaseClockSpeed = 3.3999999999999999,
                            BoostClockSpeed = 5.5999999999999996,
                            CpuCores = 20,
                            Description = "Great balance for gaming and productivity workloads.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8071514700K",
                            Name = "Intel Core i7-14700K",
                            Price = 4490m,
                            ProductCategory = 3,
                            Socket = "LGA1700",
                            Threads = 28
                        },
                        new
                        {
                            Id = 4,
                            BaseClockSpeed = 3.7999999999999998,
                            BoostClockSpeed = 4.7000000000000002,
                            CpuCores = 8,
                            Description = "High-performance AM4 processor with 8 cores.",
                            Manufacturer = "AMD",
                            ModelNumber = "100-100000063WOF",
                            Name = "AMD Ryzen 7 5800X",
                            Price = 2690m,
                            ProductCategory = 3,
                            Socket = "AM4",
                            Threads = 16
                        },
                        new
                        {
                            Id = 5,
                            BaseClockSpeed = 3.7000000000000002,
                            BoostClockSpeed = 4.7999999999999998,
                            CpuCores = 12,
                            Description = "Powerful 12-core AM4 processor for gaming and productivity.",
                            Manufacturer = "AMD",
                            ModelNumber = "100-100000061WOF",
                            Name = "AMD Ryzen 9 5900X",
                            Price = 4490m,
                            ProductCategory = 3,
                            Socket = "AM4",
                            Threads = 24
                        },
                        new
                        {
                            Id = 6,
                            BaseClockSpeed = 3.2000000000000002,
                            BoostClockSpeed = 6.0,
                            CpuCores = 24,
                            Description = "Flagship processor with maximum performance for enthusiasts.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8071514900K",
                            Name = "Intel Core i9-14900K",
                            Price = 6990m,
                            ProductCategory = 3,
                            Socket = "LGA1700",
                            Threads = 32
                        },
                        new
                        {
                            Id = 7,
                            BaseClockSpeed = 2.8999999999999999,
                            BoostClockSpeed = 4.2999999999999998,
                            CpuCores = 6,
                            Description = "6-core budget-friendly CPU, great for entry-level gaming.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8070110400F",
                            Name = "Intel Core i5-10400F",
                            Price = 1390m,
                            ProductCategory = 3,
                            Socket = "LGA1200",
                            Threads = 12
                        },
                        new
                        {
                            Id = 8,
                            BaseClockSpeed = 3.8999999999999999,
                            BoostClockSpeed = 4.9000000000000004,
                            CpuCores = 6,
                            Description = "6-core 11th gen CPU with strong single-core performance.",
                            Manufacturer = "Intel",
                            ModelNumber = "BX8070811600K",
                            Name = "Intel Core i5-11600K",
                            Price = 2190m,
                            ProductCategory = 3,
                            Socket = "LGA1200",
                            Threads = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
